import { ItemCategoryGroup, ItemCategory } from "~/types/market";

export const categoryGroupData = {
    [ItemCategoryGroup.KNIVES]: [
      ItemCategory.BUTTERFLY,
      ItemCategory.M9_BAYONET,
      ItemCategory.KARAMBIT,
      ItemCategory.KUKRI,
      ItemCategory.SKELETON,
      ItemCategory.BAYONET,
      ItemCategory.TALON,
      ItemCategory.NOMAD,
      ItemCategory.FLIP,
      ItemCategory.STILETTO,
      ItemCategory.CLASSIC,
      ItemCategory.URSUS,
      ItemCategory.HUNTSMAN,
      ItemCategory.PARACORD,
      ItemCategory.SURVIVAL,
      ItemCategory.FALCHION,
      ItemCategory.SHADOW_DAGGERS,
      ItemCategory.BOWIE,
      ItemCategory.GUT,
      ItemCategory.NAVAJA,
    ],
    [ItemCategoryGroup.GLOVES]: [
      ItemCategory.SPORT,
      ItemCategory.SPECIALIST,
      ItemCategory.MOTO,
      ItemCategory.DRIVER,
      ItemCategory.HAND_WRAPS,
      ItemCategory.BROKEN_FANG,
      ItemCategory.HYDRA,
      ItemCategory.BLOODHOUND,
    ],
    [ItemCategoryGroup.RIFLES]: [
      ItemCategory.AK,
      ItemCategory.AWP,
      ItemCategory.M4A1,
      ItemCategory.M4A4,
      ItemCategory.AUG,
      ItemCategory.SG553,
      ItemCategory.FAMAS,
      ItemCategory.GALIL,
      ItemCategory.SCOUT,
      ItemCategory.SCAR20,
      ItemCategory.GS3G1,
    ],
    [ItemCategoryGroup.PISTOLS]: [
      ItemCategory.DESERT_EAGLE,
      ItemCategory.USP,
      ItemCategory.GLOCK,
      ItemCategory.P2000,
      ItemCategory.P250,
      ItemCategory.FN57,
      ItemCategory.R8,
      ItemCategory.TEC9,
      ItemCategory.DUALIES,
      ItemCategory.CZ75,
      ItemCategory.ZEUS,
    ],
    [ItemCategoryGroup.SMGS]: [
      ItemCategory.MP9,
      ItemCategory.MAC10,
      ItemCategory.UMP45,
      ItemCategory.P90,
      ItemCategory.MP7,
      ItemCategory.BIZON,
      ItemCategory.MP5SD,
    ],
    [ItemCategoryGroup.SHOTGUNS]: [
      ItemCategory.XM1014,
      ItemCategory.MAG7,
      ItemCategory.SAWED,
      ItemCategory.NOVA,
    ],
    [ItemCategoryGroup.MACHINEGUNS]: [
      ItemCategory.M249,
      ItemCategory.NEGEV,
    ],
    [ItemCategoryGroup.STICKERS]: [],
    [ItemCategoryGroup.OTHERS]: [],
  };