export enum OrderStatus {
  SUCCESS = 'SUCCESS',
  PENDING_BUYER = 'PENDING_BUYER',
  PENDING_SELLER = 'PENDING_SELLER',
  CANCELLED_BUYER = 'CANCELLED_BUYER',
  CANCELLED_SELLER = 'CANCELLED_SELLER',
}

