import { CardCategory, CardStatus, CardType, type ICardData } from '~/types/cards'
import type { IUserProfileData } from '~/types/user'

export const useCardStore = defineStore('card', () => {
  const authStore = useAuthStore()
  const commonStore = useCommonStore()
  const toast = useToast()
  const nuxtApp = useNuxtApp()
  const i18n = nuxtApp.$i18n

  const cardList = ref<ICardData[]>([
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 1234',
      cardType: CardType.DIGITAL,
      cardCategory: CardCategory.INVESTMENT,
      balance: 100.0123123,
      totalTopup: 500,
      totalSpend: 500,
      createdAt: '2025-03-11T13:36:41.718Z',
      status: CardStatus.ACTIVE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 5678',
      cardType: CardType.PHYSICAL,
      cardCategory: CardCategory.TRAVEL,
      balance: 1200123123,
      totalTopup: 700,
      totalSpend: 500,
      createdAt: '2025-03-11T13:36:41.718Z',
      status: CardStatus.CANCEL,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 9101',
      cardType: CardType.DIGITAL,
      cardCategory: CardCategory.UTILITIES,
      balance: 1500,
      totalTopup: 800,
      totalSpend: 700,
      createdAt: '2025-03-11T13:36:41.718Z',
      status: CardStatus.FREEZE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 1121',
      cardType: CardType.PHYSICAL,
      cardCategory: CardCategory.SOFTWARE,
      balance: 2000,
      totalTopup: 1000,
      totalSpend: 500,
      createdAt: '2025-03-11T13:36:41.718Z',
      status: CardStatus.ACTIVE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 3141',
      cardType: CardType.DIGITAL,
      cardCategory: CardCategory.MARKETING,
      balance: 900,
      totalTopup: 400,
      totalSpend: 500,
      createdAt: '2025-03-11T13:36:41.718Z',
      status: CardStatus.CANCEL,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 5161',
      cardType: CardType.PHYSICAL,
      cardCategory: CardCategory.SALES,
      balance: 1300,
      totalTopup: 700,
      totalSpend: 600,
      createdAt: '2025-03-11T13:36:41.718Z',
      status: CardStatus.ACTIVE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 7181',
      cardType: CardType.DIGITAL,
      cardCategory: CardCategory.OTHER,
      balance: 1700,
      totalTopup: 900,
      totalSpend: 800,
      createdAt: '2025-03-11T13:36:41.718Z',
      status: CardStatus.FREEZE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 9202',
      cardType: CardType.PHYSICAL,
      cardCategory: CardCategory.INVESTMENT,
      balance: 1000,
      totalTopup: 500,
      totalSpend: 500,
      createdAt: '2025-03-11T13:36:41.718Z',
      status: CardStatus.ACTIVE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 1222',
      cardType: CardType.DIGITAL,
      cardCategory: CardCategory.TRAVEL,
      balance: 1400,
      totalTopup: 700,
      totalSpend: 700,
      createdAt: '2025-03-11T13:36:41.718Z',
      status: CardStatus.CANCEL,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 3242',
      cardType: CardType.PHYSICAL,
      cardCategory: CardCategory.UTILITIES,
      balance: 1600,
      totalTopup: 800,
      totalSpend: 800,
      createdAt: '2025-03-11T13:36:41.718Z',
      status: CardStatus.FREEZE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 5262',
      cardType: CardType.DIGITAL,
      cardCategory: CardCategory.SOFTWARE,
      balance: 1900,
      totalTopup: 900,
      totalSpend: 1000,
      createdAt: '2025-03-11T13:36:41.718Z',
      status: CardStatus.ACTIVE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 7282',
      cardType: CardType.PHYSICAL,
      cardCategory: CardCategory.MARKETING,
      balance: 1100,
      totalTopup: 600,
      totalSpend: 500,
      createdAt: '2025-03-11T13:36:41.718Z',
      status: CardStatus.CANCEL,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 9303',
      cardType: CardType.DIGITAL,
      cardCategory: CardCategory.SALES,
      balance: 1800,
      totalTopup: 1000,
      totalSpend: 800,
      createdAt: '2025-03-11T13:36:41.718Z',
      status: CardStatus.ACTIVE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 1323',
      cardType: CardType.PHYSICAL,
      cardCategory: CardCategory.OTHER,
      balance: 1500,
      totalTopup: 800,
      totalSpend: 700,
      createdAt: '2025-03-11T13:36:41.718Z',
      status: CardStatus.FREEZE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 3343',
      cardType: CardType.DIGITAL,
      cardCategory: CardCategory.INVESTMENT,
      balance: 900,
      totalTopup: 400,
      totalSpend: 500,
      createdAt: '2025-03-11T13:36:41.718Z',
      status: CardStatus.ACTIVE,
    },
  ])

  async function getCardList() {}

  return {
    cardList,
    getCardList,
  }
})
