import { CardCategory, CardStatus, CardType, type ICardData } from '~/types/card'
import type { IUserProfileData } from '~/types/user'

export const useCardStore = defineStore('card', () => {
  const authStore = useAuthStore()
  const commonStore = useCommonStore()
  const toast = useToast()
  const nuxtApp = useNuxtApp()
  const i18n = nuxtApp.$i18n

  const cardList = ref<ICardData[]>([
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 1234',
      cardType: CardType.DIGITAL,
      cardCategory: CardCategory.INVESTMENT,
      balance: 1000,
      totalTopup: 500,
      totalSpend: 500,
      createdAt: '20/3/2023',
      status: CardStatus.ACTIVE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 5678',
      cardType: CardType.PHYSICAL,
      cardCategory: CardCategory.TRAVEL,
      balance: 1200,
      totalTopup: 700,
      totalSpend: 500,
      createdAt: '22/3/2023',
      status: CardStatus.CANCEL,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 9101',
      cardType: CardType.DIGITAL,
      cardCategory: CardCategory.UTILITIES,
      balance: 1500,
      totalTopup: 800,
      totalSpend: 700,
      createdAt: '23/3/2023',
      status: CardStatus.FREEZE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 1121',
      cardType: CardType.PHYSICAL,
      cardCategory: CardCategory.SOFTWARE,
      balance: 2000,
      totalTopup: 1000,
      totalSpend: 500,
      createdAt: '24/3/2023',
      status: CardStatus.ACTIVE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 3141',
      cardType: CardType.DIGITAL,
      cardCategory: CardCategory.MARKETING,
      balance: 900,
      totalTopup: 400,
      totalSpend: 500,
      createdAt: '25/3/2023',
      status: CardStatus.CANCEL,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 5161',
      cardType: CardType.PHYSICAL,
      cardCategory: CardCategory.SALES,
      balance: 1300,
      totalTopup: 700,
      totalSpend: 600,
      createdAt: '26/3/2023',
      status: CardStatus.ACTIVE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 7181',
      cardType: CardType.DIGITAL,
      cardCategory: CardCategory.OTHER,
      balance: 1700,
      totalTopup: 900,
      totalSpend: 800,
      createdAt: '27/3/2023',
      status: CardStatus.FREEZE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 9202',
      cardType: CardType.PHYSICAL,
      cardCategory: CardCategory.INVESTMENT,
      balance: 1000,
      totalTopup: 500,
      totalSpend: 500,
      createdAt: '28/3/2023',
      status: CardStatus.ACTIVE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 1222',
      cardType: CardType.DIGITAL,
      cardCategory: CardCategory.TRAVEL,
      balance: 1400,
      totalTopup: 700,
      totalSpend: 700,
      createdAt: '29/3/2023',
      status: CardStatus.CANCEL,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 3242',
      cardType: CardType.PHYSICAL,
      cardCategory: CardCategory.UTILITIES,
      balance: 1600,
      totalTopup: 800,
      totalSpend: 800,
      createdAt: '30/3/2023',
      status: CardStatus.FREEZE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 5262',
      cardType: CardType.DIGITAL,
      cardCategory: CardCategory.SOFTWARE,
      balance: 1900,
      totalTopup: 900,
      totalSpend: 1000,
      createdAt: '31/3/2023',
      status: CardStatus.ACTIVE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 7282',
      cardType: CardType.PHYSICAL,
      cardCategory: CardCategory.MARKETING,
      balance: 1100,
      totalTopup: 600,
      totalSpend: 500,
      createdAt: '1/4/2023',
      status: CardStatus.CANCEL,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 9303',
      cardType: CardType.DIGITAL,
      cardCategory: CardCategory.SALES,
      balance: 1800,
      totalTopup: 1000,
      totalSpend: 800,
      createdAt: '2/4/2023',
      status: CardStatus.ACTIVE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 1323',
      cardType: CardType.PHYSICAL,
      cardCategory: CardCategory.OTHER,
      balance: 1500,
      totalTopup: 800,
      totalSpend: 700,
      createdAt: '3/4/2023',
      status: CardStatus.FREEZE,
    },
    {
      cardName: 'Nguyen Hong Ngoc',
      cardNumber: 'xxxx xxxx xxxx 3343',
      cardType: CardType.DIGITAL,
      cardCategory: CardCategory.INVESTMENT,
      balance: 900,
      totalTopup: 400,
      totalSpend: 500,
      createdAt: '4/4/2023',
      status: CardStatus.ACTIVE,
    },
  ])

  async function getCardList() {}

  return {
    cardList,
    getCardList,
  }
})
